language: python
python:
 - "3.5"
before_install:
 - pip install pytest pytest-cov
 - pip install coveralls
script: 
 - py.test coveralls/tests_rpn.pyy --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing 
after_success:
 - coveralls


